pull_request_rules:
  - name: auto merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
      delete_head_branch: {}
