pull_request_rules:
  - name: automatic merge for Dependabot pull requests after CI passes
    conditions:
      - author=dependabot-preview
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}
