pull_request_rules:
  - name: auto merge on CI success
    conditions:
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
      delete_head_branch: {}
