pull_request_rules:
  - name: automatic merge for Dependabot pull requests after CI passes
    conditions:
      - author=dependabot-preview[bot]
      - label=dependencies
      - base=master
    actions:
      merge:
        method: merge
      delete_head_branch: {}
